language: elixir
elixir:
  - 1.7.4
  - 1.6.6
otp_release:
  - 20.0
  - 21.0
sudo: false # to use faster container based build environment
env:
  - MIX_ENV=test
install:
  - mix do local.hex --force, local.rebar --force
  - mix deps.get # need to explicitly get test deps, see mix.exs
  - mix compile
script:
  - mix test
matrix:
  exclude:
    - otp_release: 20.0
      elixir: 1.3.4
